- examples/bop_object_physics_positioning/README.md
- examples/bop_object_physics_positioning/config.yaml
- src/lighting/LightModule.py
- src/loader/BopLoader.py
- src/provider/sampler/Shell.py
- src/provider/sampler/UniformSO3.py
The extension of UniformSO3 allows selecting which axes to rotate around. This is useful, e.g., for the generation of initial object poses in bop_object_physics_positioning. In datasets such as LineMod, the objects are always standing up-right in the test images. Hence, we want to randomize the orientation of the objects only around the Z-axis (i.e. the up-right axis).
> Bug fixes and an extension of UniformSO3

- examples/bop_object_physics_positioning/config.yaml
- src/writer/BopWriter.py
The BOP writer now stores the full dataset (including images) in the BOP format.
The writer assumes that self._find_registered_output_by_key("depth") provides depth images (i.e. the Z coordinate is saved at each pixel). However, currently, this provides distance images (i.e. the distance from the optical center is saved at each pixel). I assume this is a bug that will be fixed in the next release.
> A new version of the BOP writer

- src/writer/ObjectStateWriter.py
- src/writer/StateWriter.py
**Background:**
When the ObjectStateWriter and the Hdf5Writer is in config.yaml the object id and object poses are written to the .hdf5 file. The id corresponds to the blender scene and there is no information which original 3D-object (e.g. obj_000001.ply or ape.ply) the given information belongs to. 
**Enhancement:**
Add the attribute "name" to ObjectStateWriter, so that the name information of the original .ply-object is written to the file as well.
> Change ObjectStateWriter so the attribute name is written as well

- examples/bop_object_physics_positioning/config.yaml
As discussed in Issue #37，I think this [line](https://github.com/DLR-RM/BlenderProc/blob/2bc01e2224d8b11e81af730fbdf48e56f39be2e5/examples/bop_object_physics_positioning/config.yaml#L171) should be deleted so as not to confuse others
> solves: iss_37 delete unnecessary line

- src/provider/sampler/Sphere.py
Hi,  
When I try this module in camera.CameraSample with mode="INTERIOR", it will raise the error `AttributeError: module 'numpy.random' has no attribute 'unform'`.
Here is the module I added to the pipeline.
```
{
"module": "camera.CameraSampler",
"config": {
"cam_poses": [
{
"number_of_samples": 10,
"location":{
"provider":"sampler.Sphere",
"center":[0, 0, 0],
"radius": 2,
"mode": "INTERIOR"
},
"rotation": {
"format": "look_at",
"value": [0,0,0],          
"inplane_rot": {
"provider": "sampler.Value",
"type": "float",
"min": -0.7854,
"max": 0.7854
}
}
}
]
}
},  
```
> fix typo in src_sampler_Sphere_py

- examples/shapenet/README.md
- examples/shapenet/config.yaml
- scripts/saveAsImg.py
- src/renderer/RgbRenderer.py
- src/writer/WriterInterface.py
Details of how to include/exclude the parameters to write the alpha channel in examples/shapenet/README.md. Related to #71
> updated to allow the option of recording the alpha channel for a transparent background in renderings

- blenderproc/python/camera/CameraValidation.py
We should first check whether `hit_object` is None before creating a `Struct`.
closes [#326](https://github.com/DLR-RM/BlenderProc/issues/326)
> fix(camera): avoid creating struct with none in visible_objects

- examples/basics/material_manipulation/README.md
> Typo fix: correct the path in the README for the image folder (material manipulation)

- examples/advanced/random_backgrounds/main.py
The category id of the only object in the random_background example was set to `0` and therefore ignored when writing coco annotations.
Also it was set very uninventively via the default parameter.
Fixes: #393
> fix(example): Fixes category id in random_background example

- blenderproc/python/utility/InstallUtility.py
Since version 2.93.1 the subfolder of the .zip portable
installation for Windows is no longer called "blender-windows64",
but "blender-{major}.{minor}-windows-x64". This commit sets the
correct blender_run_path for Windows and blender version > 2.93.
If at some point, downwards compatibilty of BlenderProc to older
Blender versions is implemented, the assignment of blender_run_path
has to be adjusted accordingly to account for the different naming
conventions by Blender.
closes #412
> fix(utility): Set correct blender_run_path

- .gitignore
When using a local installation (via `pip install [-e] .`), the
folders `blenderpoc.egg-info/` and `build/` are created, which
should not be tracked by git.
Fixes #439
> feat: Add local build folders to .gitignore

- blenderproc/python/types/MeshObjectUtility.py
Up to now, `scale` is applied in `create_primitive()` to the
primitive after its creation. The reason for this was a bug in
Blender which ignored the `scale` argument in
`bpy.ops.mesh.primitive_..._add()`. This seems to be fixed by now,
so the scaling inside BlenderProc results in applying the scaling
twice.
This commit fixes this bug in BlenderProc by deleting the second
scaling.
fixes #432
> fix(types): Do not apply `scale` twice on primitive

- blenderproc/python/renderer/RendererUtility.py
> fix(renderer): Improves the error message when rendering without having any registered camera poses

- blenderproc/python/types/MeshObjectUtility.py
This commit sets the cursor position back to its original
position after changing the origin of an object.
Fixes #451
> fix(types): Fix `set_origin()`

- blenderproc/python/object/ObjectPoseSampler.py
`sample_pose()` now allows to define its behavior when the current
object could not be placed without collision. Additionally it
returns a `Dict` containing the objects to sample as keys and a
Tuple with the number of attempts to place the respective object
and whether it was succesful or not.
Fixes #435
> feat(object): Improve `sample_pose()`

- examples/datasets/bop_challenge/main_hb_random.py
- examples/datasets/bop_challenge/main_icbin_random.py
- examples/datasets/bop_challenge/main_itodd_random.py
- examples/datasets/bop_challenge/main_lm_upright.py
- examples/datasets/bop_challenge/main_tless_random.py
- examples/datasets/bop_challenge/main_tudl_random.py
- examples/datasets/bop_challenge/main_ycbv_random.py
- examples/datasets/bop_object_on_surface_sampling/main.py
- examples/datasets/bop_object_physics_positioning/main.py
- examples/datasets/bop_object_pose_sampling/main.py
- examples/datasets/bop_scene_replication/main.py
#485 
This should reduce the rendering time a lot and allows generating the original BOP data.
> Fix(BOP): Reset max samples to 50

- blenderproc/__init__.py
- blenderproc/external/vhacd/decompose.py
- blenderproc/python/camera/LensDistortionUtility.py
- blenderproc/python/modules/renderer/RendererInterface.py
- blenderproc/python/renderer/RendererUtility.py
- blenderproc/python/utility/DefaultConfig.py
- blenderproc/python/utility/Initializer.py
- blenderproc/python/utility/InstallUtility.py
- blenderproc/python/utility/SetupUtility.py
- blenderproc/python/writer/GifWriterUtility.py
- blenderproc/scripts/visHdf5Files.py
- examples/basics/material_manipulation/config.yaml
Fixes #513 
* switches to blender 3.1 and python 3.10
* raises version numbers on used python packages
* add gpu support for METAL on mac os above 12.3
> Iss 513 switch to blender 3.1

- blenderproc/python/renderer/SegMapRendererUtility.py
fix bug in blender, if there are too many objects in a scene by turning off the sample_as_light option for the materials, removing the multiple importance sampling for them.
This bug fix was provided by: @jascase901
> fix(segmaprenderer): fix too many objects in seg scene

- blenderproc/python/writer/CocoWriterUtility.py
> fix(coco): Makes coco annotation writer working with frame_start != 0

- .gitignore
- blenderproc/external/vhacd/build_linux.sh
Default cmake mode seemed to be Debug. After setting it to Release, vhacd is fast again.
Fixes: #621
> fix(vhacd): Sets cmake release mode to vhacd build script

- blenderproc/python/loader/ObjectLoader.py
With blender 3.2 came a new experimental obj loader (which is not used per default). The new loader seems to be about 10x faster!
> feat(loader): Switches to new (experimental) obj loader

- blenderproc/__init__.py
blenderproc pip install ignored dependencies that were already installed in the python user packages path. This was caused by the PYTHONPATH env variable which we set to be the parent dir of the inner blenderproc directory. If blenderproc is installed via pip, this might be the (user) site-packages path.
Now the PYTHONPATH env var is emptied right after loading the blenderproc module, so there should be no complications anymore.
Fixes: #627
> fix(pip): Fixes pip installs when the blenderproc pip package is used

- blenderproc/__init__.py
In debug mode, our `__init__.py` script is run each time the script is run. After #629 this leads to an error as the env var has already been deleted and does not exist anymore.
> fix(debug): Fixes running script in debug multiple times

- blenderproc/python/renderer/SegMapRendererUtility.py
When an hdri image is used, the hdri texture node is connected with the output node and the background node gets disconnected, see https://github.com/DLR-RM/BlenderProc/blob/main/blenderproc/python/loader/HavenEnvironmentLoader.py#L32
Therefore, changing the background node in the segmap renderer has no effect and leads to the hdri image being rendered into the segmap image which then leads to the "too many colors" error.
Fixes: #467
> fix(segmap): Fixes segmap rendering when an hdri image is used as background

- blenderproc/python/loader/BlendLoader.py
- blenderproc/python/types/EntityUtility.py
- blenderproc/python/types/LightUtility.py
- blenderproc/python/types/MeshObjectUtility.py
- tests/testEntity.py
**Merge first: #633**  
* Puts all children / parent methods into the entity class
* get_children() and get_parent() now use `convert_to_entity_subclass` to return the blender objects wrapped into the correct class
* Adds tests
Fixes #636
> Iss 636 parent cleanup

- blenderproc/__init__.py
- blenderproc/api/renderer/__init__.py
- blenderproc/python/modules/main/InitializerModule.py
- blenderproc/python/renderer/RendererUtility.py
- blenderproc/python/utility/DefaultConfig.py
- blenderproc/python/utility/Initializer.py
* the complete device selection code moved to the renderer as `bproc.renderer.set_render_devices()` (I think this makes the most sense, as the device is used for rendering)
* `set_render_devices` has three clear parameters: `use_only_cpu`, `desired_gpu_device_type`, `desired_gpu_ids` which should cover all cases (let me know if it doesn't)
* `bproc.cleanup()` can now be used to clean up the scene via the public api, no need to call the init function multiple times
* Calling init multiple times now throws an error
* `horizon_color` and `use_experimental_features` parameters were removed from the init function. They can be set via `bproc.renderer.set_world_background()` and `bproc.renderer.enable_experimental_features()`
Fixes: #631 
Fixes: #585
> Refactors bproc.init function

- blenderproc/python/writer/BopWriterUtility.py
> fix(BopWriter): remove encoding on writing a binary file

- blenderproc/python/types/LinkUtility.py
- blenderproc/python/types/URDFUtility.py
Addresses #736. Adds multiplication of parent pose to a joint's local2world matrix to have location changes correctly calculated.
> #736: incorporate location changes to urdf local2world matrix calculations

- blenderproc/python/object/PhysicsSimulation.py
- blenderproc/python/renderer/FlowRendererUtility.py
- blenderproc/python/renderer/NOCSRendererUtility.py
- blenderproc/python/renderer/RendererUtility.py
- blenderproc/python/utility/DefaultConfig.py
- blenderproc/python/utility/Utility.py
The output for the basic example now looks like this:
```
Selecting render devices...
Device GeForce GTX 1070 Ti of type CUDA found and used.
Device Intel Core i5-2500K CPU @ 3.30GHz of type CPU found and used.
Timer 'OBJ_import' took 3.0 ms
Rendering 2 frames of colors, normals...
Finished rendering after 10.776 seconds
Merging data for frame 0 into examples/basics/basic/output/0.hdf5
Merging data for frame 1 into examples/basics/basic/output/1.hdf5
```
Fixes: #732
> Suppresses blender debug prints during rendering and physics simulation

- blenderproc/python/object/ObjectPoseSampler.py
A typo caused the rotation not to be set if the mode on failure was set to `initial_pose` inside the sample pose function
fix #757 
Many thanks to: @andrewyguo
> fix(ObjectPoseSampler): for the mode on failure the rotation was not set

- blenderproc/python/utility/InstallUtility.py
This PR also fixes a bug in the renaming of the new blender folder. Before, there was no distinction between minor versions, so the old blender 3.3.0 folder would have been also be renamed to 3.3.1.
> feat(blender): Upgrades to blender 3.3.1

- blenderproc/python/object/ObjectReplacer.py
- blenderproc/python/types/StructUtility.py
- examples/advanced/coco_annotations/main.py
- Addresses issue #760  
- fix the return type of get_all_cps()
- now returns a list of (key, value) pairs instead of IDPropertyGroupViewItems
- Matches documentation: https://dlr-rm.github.io/BlenderProc/blenderproc.python.types.StructUtility.html#blenderproc.python.types.StructUtility.Struct.get_all_cps
> fix(types): fix return type of get_all_cps()

- blenderproc/python/utility/InstallUtility.py
In some environment like Docker, $USER might not be set https://stackoverflow.com/questions/54411218/docker-why-isnt-user-environment-variable-set 
`getpass.getuser` checks the environment variables LOGNAME, USER, LNAME and USERNAME, in order, and returns the value of the first one which is set to a non-empty string. If none are set, the login name from the password database is returned on systems which support the pwd module, otherwise, an exception is raised.
> Get env:USER in a more reliable way

- examples/datasets/bop_object_pose_sampling/main.py
After #693 custom properties should not start with `cp_` anymore. Thats why the bop_object_pose_sampling does not produce any coco annotations at the moment
> fix(examples): Fixes usage of custom properties in bop_object_pose_sampling example

- blenderproc/python/writer/BopWriterUtility.py
Only writes masks for objects given in `target_objects`. If `target_objects` is not given, use `dataset`
Closes #807
> fix(#807): use target_objects in write_bop

- blenderproc/python/renderer/RendererUtility.py
Fixes #815 
After investigating the issue, I initially expected `stdout_redirected` to be responsible for the file handle leak. As it turns out, this is not the case. Simply closing the pipes after the rendering works.
We have to add a `try .. except` for the closing because `pipe_in` is changed (maybe even closed?) inside the `stdout_redirected`, therefore closing it again does not work.
> fix(#815): Add closing the pipe handles

- blenderproc/python/writer/BopWriterUtility.py
Since the bop_toolkit vispy renderer inherits from app.canvas it's a canvas object itself. Since the canvas is only initialized when the renderer is initialized, the focus is lost when another renderer instance is created. This can be solved by adding  `ren.set_current()` (see https://vispy.org/api/vispy.app.canvas.html) after the 'creation' (since it's an argument based singleton, it will just return an instance with the same arguments) of the renderer.
This examples, compared to the code shown in #832, solves the issue:
```python
import blenderproc as bproc
from bop_toolkit_lib import inout, misc, visibility, renderer
import numpy as np
while 1:
width = 128
height = 720
print("1. START")
ren = renderer.create_renderer(width=width, height=height, renderer_type='vispy', mode='depth') …
```
> fix(832): Set renderer canvas current canvas

- blenderproc/python/loader/ObjectLoader.py
Small fix for #821. Uses `bpy.ops.wm.stl_import` instead of `bpy.ops.import_mesh.stl` to match the default parameters listed in https://github.com/DLR-RM/BlenderProc/blob/84ac7dff1351a36f2bde92888590e7cb48e1704b/blenderproc/python/loader/URDFLoader.py#L337
> fix(#821): correctly load .stl objects in urdf files

- blenderproc/scripts/download_haven.py
This pull request is linked to Issue #847 
Changes are as follows: 
1. Use of a thread pool where tasks are executed in parallel. 
2. Added progress bar for downloads instead of writing which file is being downloaded
3. Check if files exists beforehand. Skip download if true. 
Performance test:
- Before change: 15 min 15 s
- After change: 5 min 2 s
Test was made with a 300 Mbit/s internet connection.
> Refactored to download in parralel

- blenderproc/scripts/download_haven.py
I recently made a pull request for refactoring the haven download script to be sequential, it was to address  #847 .
I noticed a potential problem where a system could crash if it has less than 4 threads, but the default is set to 4
Fixed it by creating a check where the `num_workers` is set to the lowest of either the system thread count or the argument thread count.
> Fixed bug where default thread count exeed system thread count for haven download script

- .pylintrc
- blenderproc/python/camera/LensDistortionUtility.py
- blenderproc/python/loader/ObjectLoader.py
- blenderproc/python/postprocessing/PostProcessingUtility.py
- blenderproc/python/postprocessing/StereoGlobalMatching.py
- blenderproc/python/types/LinkUtility.py
- blenderproc/python/utility/SetupUtility.py
- blenderproc/python/writer/BopWriterUtility.py
- blenderproc/scripts/download_haven.py
- examples/advanced/urdf_loading_and_manipulation/README.md
- examples/advanced/urdf_loading_and_manipulation/main.py
* All loaded objects get a model_path cp (this should fix the camera_object_pose example)
* In the urdf example, I now disabled `calc_mask_info_coco`, as setting the model_path for links is difficult (one link can have zero or multiple visuals)
* `get_inertial_local2world_mat` of the link class now also works with no parameter given (necessary for bopwriter)
* Fixes some pylint complaints
> Adds model_path cp to loaded objects

- blenderproc/scripts/vis_coco_annotation.py
numpy.bool is deprecated https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
closes #863
> fix(vis_coco_annotation): changed np.bool to bool

- blenderproc/python/utility/DefaultConfig.py
- blenderproc/python/utility/Utility.py
When blenderproc is installed via pip, no git version can be retrieved. Also on windows it is not supported. Therefore, I am removing the dependency, as it is not so useful anyway.
Related: #872
> fix(utils): Removes git dependency

- blenderproc/python/writer/BopWriterUtility.py
Only save unique categories for the scene_gt_json annotations in the BOP writer. 
Response to issue #883
I initially tried to do 
```python
CATEGORIES = list(set(CATEGORIES))  
```
But because `CATEGORIES` is a list of dicts it is not possible, because a dict is not hashable. 
I found an answer on the following stack overflow thread: https://stackoverflow.com/questions/9427163/remove-duplicate-dict-in-list-in-python
> Fix dublicate Categories

- blenderproc/python/types/LinkUtility.py
- blenderproc/python/types/MeshObjectUtility.py
- blenderproc/python/utility/DefaultConfig.py
- blenderproc/python/writer/BopWriterUtility.py
- examples/advanced/urdf_loading_and_manipulation/main.py
#830 
replaces the vispy renderer in `write_bop()` with pyrenderer. 
directly converts the `MeshObjects` into `trimesh.Trimesh` objects, so we don't need to reload anything here.
whole process itself is pretty fast (should be ~ 1s for 25 frames for a single object)
tested by generating some bop dataset scenes; results look as expected (but there's still a test regarding this right?)
> Iss830 write bop renderer

- blenderproc/python/writer/BopWriterUtility.py
> fix(#912): coco writer if annotations are empty

- blenderproc/python/types/MeshObjectUtility.py
#914 
Some quad meshes are dirty and contain some triangles as well. In that case only include the quad faces.
> fix(#914): Allow quad meshes to be converted to trimesh

- blenderproc/python/renderer/RendererUtility.py
UTF-8 has multi-byte characters, and if blender outputs those `.decode()` will raise an Exception.
UTF-8 multi-byte characters will not contain any ASCII bytes. Thus, I changed `.decode` into `chr` to mitigate the issue. The solution will not interfere with `\b` detection.
Sample error script:
https://github.com/liuyulinn/objaverse/blob/master/objaverse1.py
Sample error glb:
[ed3357efe63547e18f5798b273514923.zip](https://github.com/DLR-RM/BlenderProc/files/11619791/ed3357efe63547e18f5798b273514923.zip)
Run the script with:
```bash
blenderproc run objaverse1.py --object-path "ed3357efe63547e18f5798b273514923.glb"
```
> Fix render progress bar issue with non-ASCII.

- blenderproc/python/renderer/FlowRendererUtility.py
RGB should now no longer overwrite optical flow output, even when output_format is set to exr.
Fixes: #684
> fix(flow): Fixes optical flow rgb output key

- blenderproc/python/utility/InstallUtility.py
> fix(windows): Fixes usage of custom blender path on windows

- blenderproc/python/loader/CCMaterialLoader.py
> fix(cctextures): Adapts cctextures loader to new filenames

- blenderproc/python/types/LightUtility.py
When calling _pattern.ravel()_, there is an issue with integer casting, which results in the array values being cast from floats to integers.  As a result, the end values are either 0 or 1, leading to the loss of color information and, consequently, the creation of an incorrect result image with only the color values cyan, yellow, and magenta.
> fix: integer cast issue for colored projector patterns

- blenderproc/python/writer/BopWriterUtility.py
calc_gt_mask and calc_gt_info can now be calculated in parallel across multiple cpu processes, which should reduce the execution time significantly when having a scene with many objects. For 300 objects, the bop writer execution time reduces from 60s to 12s with 8 cores
Resolves: #994
> feat(bop): Adds multiprocessing to the bop writer

- blenderproc/python/utility/InstallUtility.py
> fix(blender): Fixes blender download

- blenderproc/python/loader/CCMaterialLoader.py
- tests/testLoader.py
> feat(ccmaterials): Skip transparent cc materials per default

- blenderproc/python/writer/CocoWriterUtility.py
> fix(coco): Fixes skipping annotation indices when appending coco annotations

- blenderproc/python/types/EntityUtility.py
- blenderproc/python/types/MeshObjectUtility.py
> feat(entity): Move hide and is_hidden methods to Entity

- blenderproc/python/renderer/RendererUtility.py
The progressbar should be updated based on the number of frames completed instead of the frame number.
closes #1037
> fix(renderer): progressbar frame offset

- blenderproc/python/writer/BopWriterUtility.py
when target_objects is not None, iterate target_objects instead of get_all_mesh_objects() to print correct warnings.
closes #1056
> fix(writer): eliminate uncorrect warning in write_bop

- blenderproc/python/loader/BlendLoader.py
fix(blendloader): add `hair_curves` support in blendloader
`valid_object_types` is not defined correctly, it should also have a curves in the list since as of Blender 3.3 it differentiates between curve and curves depending on the new hair system. See: https://github.com/DLR-RM/BlenderProc/issues/1050 for more details.
closes #1050
> Update BlendLoader.py to also transfer hair_curves

- blenderproc/python/loader/ObjectLoader.py
extension of the load_obj module allows loading .usd/.usdc/.usda files and load it as a scene
closes #1029
> feat(loader): add usd scene loader

- blenderproc/python/types/MeshObjectUtility.py
> feat(MeshObjectUtility): convert quads to triangles

- tests/README.md
Fixes https://github.com/DLR-RM/BlenderProc/issues/1139.
Fix spelling: "cc_matrials_path" -> "cc_materials_path".
Add apostrophe "blenderprocs" -> "blenderproc's".
Make download command's URL absolute.
> doc(tests): minor text fixes.

- blenderproc/python/types/EntityUtility.py
This makes sure that the rotation is set to euler xyz. This does not automatically happen (found it when importing a glb object)
Otherwise (if the rotation is for example set to quaternion), the rotation does not change.
> Make sure object rotation is set in XYZ-Euler coordinates

- blenderproc/python/loader/BlendLoader.py
When using
```
bproc.loader.load_blend("my.blend", data_blocks=["objects", "collections"])
```
the hierarchies between collections and objects should now be preserved. 
@johan-apes I think I found an easier way to fix the collection hierarchies. Could you please check whether this fix also works for you?
> fix(loader): Preserves collection hierarchies when importing them from blend file

- blenderproc/python/utility/Initializer.py
> fix(init): Makes sure world nodes are enabled after clean_up()

- blenderproc/python/types/MeshObjectUtility.py
- Add parameters `point_size` and `point_color` to `create_from_point_cloud`
- Streamline point cloud creation using `from_pydata` for points and the `GeometryNodeMeshToPoints` node
- Points are now perfect spheres instead of low-res ico-spheres
> feat(object): enhance point cloud creation

- blenderproc/api/lighting/__init__.py
- blenderproc/python/types/LightUtility.py
- blenderproc/python/utility/BlenderUtility.py
Similar to the utility functions in `MeshObjectUtility` this PR does:
- Introduce `get_all_blender_light_objects` to retrieve all light objects in the scene
- Add `convert_to_lights` to convert Blender light objects to BlenderProc light objects
- Creates `get_all_light_objects` to combine the above functionalities for easier access to light objects
> feat(light): add utility functions for managing light objects

- blenderproc/python/types/MeshObjectUtility.py
- Introduce methods to get all modifiers and one specific modifier, similar to `get_materials`
- Update existing methods to return modifiers to facilitate subsequent changes to the modifier
- Add type hints for better clarity and type checking
- Improve comments
- Refactor `add_auto_smooth_modifier` to use new methods
> feat(object): enhance MeshObjectUtility with new methods and type hints

- blenderproc/python/loader/BlendLoader.py
fix(loader): Fix TypeError on line 89
This fix will allow BlenderProc to render scenes which rely on animations within the blend file to define frames.
closes #1206
> fix(loader): Fix TypeError on line 89
