DLR-RM/BlenderProc

src/camera/CameraModule.py, src/writer/BopWriter.py
=> hotfix: BopWriter now can handle overwritten intrinsics by CameraModule

src/object/PhysicsPositioning.py
#33
Origin shifting, which is necessary for physics to work correctly, and resulting misalignments are fixed.
=> fix(PhysicsPositioning): incorporate rotation in object coordinates

examples/bop_object_on_surface_sampling/README.md
=> Update README.md (minor typo correction)

run.py
I was having trouble getting this running and after some investigation it seemed this path was not constructed correctly, making the included change fixed the issue.  Running Blender 2.83.3
=> update pre_python_package_path to include Contents/Resources

run.py
Address the problem described in https://github.com/DLR-RM/BlenderProc/issues/69
It could be also addressed with a separate `if`...`elif`...`else` statement but since this is done already just a few lines before. Thus, I chose to include it there. If you believe that it should be addressed in its own `if` statement let me know so that I can change it.
=> update run.py script regarding the blender installation folder structure and different platforms

run.py, scripts/generate_nice_vis_rendering.py, src/main/Module.py, src/run.py, src/utility/Utility.py
Blender is cross-platform. So BlenderProc is.
I fixed some paths and args that don't work on Windows.
Then BlenderProc works on Windows now.
=> add support for Windows

run.py, src/debug.py
1. Allows debugging on Windows, which was missing in last merge.
2. Fixes the username and home environment variables on Windows.
=> Fixes support on Windows

blenderproc/python/writer/CocoWriterUtility.py
Addresses https://github.com/DLR-RM/BlenderProc/issues/328
=> feat(coco_prefix): add prefix to coco image file paths.

python-app.yml
Add a new github workflow to automatized run the BlenderProcHelper script before merging.
Fixes #342
=> feat(github_workflow): add a github workflow to run BlenderProcHelper

blenderproc/scripts/visHdf5Files.py
=> fix(vis_hdf5): fix the comparison of the keys to regex

blenderproc/debug_startup.py
=> fix(debug): Fixes debugging with relative script paths on windows

blenderproc/python/lighting/SuncgLighting.py, blenderproc/python/lighting/SurfaceLighting.py, blenderproc/python/loader/Front3DLoader.py, blenderproc/python/modules/lighting/SurfaceLightingModule.py, blenderproc/python/modules/manipulators/MaterialManipulator.py, blenderproc/python/types/MaterialUtility.py, examples/datasets/scenenet/README.md, examples/datasets/scenenet/config.yaml, examples/datasets/scenenet/main.py, examples/datasets/scenenet_with_cctextures/config.yaml, examples/datasets/scenenet_with_cctextures/main.py, examples/datasets/shapenet_with_scenenet/config.yaml, examples/datasets/shapenet_with_scenenet/main.py
=> remove keep_using_base_color from light_surface and make_emissive

examples/advanced/random_room_constructor/config.yaml, examples/advanced/random_room_constructor/main.py, examples/datasets/scenenet/config.yaml, examples/datasets/scenenet/main.py, examples/datasets/scenenet_with_cctextures/config.yaml, examples/datasets/scenenet_with_cctextures/main.py, examples/datasets/shapenet_with_scenenet/config.yaml, examples/datasets/shapenet_with_scenenet/main.py
=> Fix(light_surface): explicit emission color

README.md, blenderproc/command_line.py, blenderproc/python/utility/SetupUtility.py
=> chore(readme): Adds docu of how to debug with IDEs

blenderproc/scripts/vis_coco_annotation.py
=> fix(coco): Fixes vis coco when category name is an int

change_log.md
=> Typos in changelog

blenderproc/python/utility/SetupUtility.py
=> fix(SetupUtility): fix the python bin and package path for Mac OS

blenderproc/__init__.py
Currently, the stack summary is checked on startup of BlenderProc,
in order to determine whether it has been called correctly (i.e.
either via the `blenderproc` command or the command line script).
This has not worked on Windows, since the stack trace differs
from the one on Linux, and hence an exception is thrown by
__init__.py.
This commit fixes this issue by performing different checks of
the stack trace depending on the current OS. Additionally, the
check for Linux was rewritten to be understandable more easily.
Fixes #358
=> fix(blenderproc): Fix __init__.py for Windows

README.md, blenderproc/command_line.py
=> Iss 427 add quickstart

blenderproc/scripts/quickstart.py
#474
forgot to add the `quickstart.py` script
=> Fix(quickstart.py): Actually add the script

docs/tutorials/key_frames.md
=> chore(key_frames): Docu for non-keyframeable properties

blenderproc/python/utility/Utility.py
.. output entries with the same key.
Fixes #533
=> Fix(Utility): Replace instead of ignore

blenderproc/python/writer/BopWriterUtility.py
=> fix(bop): Fixes writing images with alpha channel using bop writer

blenderproc/external/vhacd/build_linux.sh, blenderproc/external/vhacd/decompose.py
Fix #607 
Not done yet.
Waiting for fix in vhacd: https://github.com/kmammou/v-hacd/pull/116
=> Iss 607 fix vhacd for version 4

blenderproc/python/loader/HavenMaterialLoader.py, blenderproc/python/material/MaterialLoaderUtility.py
=> Iss 604 return list for haven mat loader

blenderproc/python/utility/InstallUtility.py
=> feat(Apple Silicion): support of apple silicion

blenderproc/api/material/__init__.py, blenderproc/python/material/MaterialLoaderUtility.py, blenderproc/python/types/MaterialUtility.py, tests/testLoader.py
=> Iss 594 add material generation based on texture

blenderproc/python/loader/HavenMaterialLoader.py, blenderproc/python/types/MeshObjectUtility.py, tests/testHavenLoader.py
=> Iss 475 simpler loading of haven materials

blenderproc/python/loader/HavenMaterialLoader.py, blenderproc/python/types/MeshObjectUtility.py, tests/testHavenLoader.py
=> Move new_random_haven_material to HavenMaterialLoader to avoid imports

blenderproc/python/loader/URDFLoader.py
=> Fix(URDFLoader): adapt to blender api change

blenderproc/scripts/download_cc_textures.py
fix #657 
Solves all cctexture related problems.
=> feat(ambientCG): fix download link, add automatic option to resume download

blenderproc/python/types/MeshObjectUtility.py
=> fix(MeshObject): fix the move_origin_to_bottom_mean_point fct.

blenderproc/python/loader/URDFLoader.py, blenderproc/python/types/InertialUtility.py, blenderproc/python/types/LinkUtility.py, blenderproc/python/types/URDFUtility.py
Fix several pylint warnings for URDF-related files
=> Iss 672 improve code with pylint

blenderproc/python/loader/BopLoader.py
=> feat(boploader): add hope support

blenderproc/version.py, change_log.md
=> feat(2.5.0): add changelog

blenderproc/python/renderer/RendererUtility.py
I opened an issue concerning this problem. I fixed it temporarily for myself with three lines of code. Thus I thought to just send a pull request to add it to your main repository as well.
=> Runs on CPU

blenderproc/python/postprocessing/PostProcessingUtility.py, blenderproc/python/writer/CocoWriterUtility.py, blenderproc/scripts/visHdf5Files.py, examples/advanced/stereo_matching/main.py
=> Iss 751 stereo segmentation

CONTRIBUTING.md, blenderproc/python/writer/CocoWriterUtility.py
=> feat(writer): add option to indent COCO annotations

.github/workflows/blenderprochelper.yml, .pylintrc, blenderproc/python/loader/AMASSLoader.py, blenderproc/python/postprocessing/PostProcessingUtility.py, blenderproc/python/renderer/RendererUtility.py, blenderproc/python/types/LinkUtility.py, blenderproc/python/types/URDFUtility.py, blenderproc/python/utility/Utility.py, blenderproc/python/writer/BopWriterUtility.py, blenderproc/python/writer/CocoWriterUtility.py, tests/run_all.py, tests/testCamera.py, tests/testEntity.py, tests/testLoader.py, tests/testUtility.py
Now all tests should pass except stereo_matching and suncg_with_object_replacer which will be fixed by blender 3.3.1.
=> Some fixes to make tests pass again

README.md, tests/README.md, tests/testCamera.py
*  Adds docu about how to run unit tests
* Fixes precision in assertAlmostEqual
Fixes: #771
=>  Adds docu about how to run unit tests

blenderproc/python/loader/HavenEnvironmentLoader.py
=> feat(hdri): Allows setting brightness of hdri backgrounds

CONTRIBUTING.md, blenderproc/python/writer/CocoWriterUtility.py
Corrects a spelling error in CocoWriterUtility.py. Also fixes a likely copy-paste error in CONTRIBUTING.md
closes #785
=> fix(loader): fix spelling error in cocowriter

blenderproc/python/writer/BopWriterUtility.py
Fixes #810 
Wait until bop_toolkit PR https://github.com/thodan/bop_toolkit/pull/82 is merged.
=> fix(#810): Remove vispy reinitialization

README.md, blenderproc/python/loader/ObjectLoader.py
Load fbx as discussed in https://github.com/DLR-RM/BlenderProc/issues/856
=> iss_856_feature_load_fbx

blenderproc/python/object/OnSurfaceSampler.py
#910
Basically, the fix proposed here:
https://github.com/DLR-RM/BlenderProc/issues/579#issuecomment-1120757860
=> fix(#910): hiding instead of deleting in sample_poses_on_surface()

blenderproc/python/types/MeshObjectUtility.py
=> fix(mesh): Fixes uv mapping by selecting all faces

blenderproc/python/types/EntityUtility.py, blenderproc/python/types/MeshObjectUtility.py, tests/testEntity.py
=> feat(entity): Rework duplicate method

blenderproc/python/utility/Initializer.py
=> fix(init): Fixes cleanup of scene properties

blenderproc/python/types/EntityUtility.py
=> fix(entity):  Fix duplicate linked for hierarchy.

blenderproc/python/types/MeshObjectUtility.py
=> fix(bvh tree creation): avoid leaving orphan meshes

blenderproc/python/utility/Initializer.py
=> fix(cleanup): Fixes scene custom prop removal

blenderproc/command_line.py
=> fix(cli): added missing 'f-strings' in argument helps
